apiVersion: v1
kind: ReplicationController
metadata:
  name: selenium-node-chrome-rep
spec:  
  replicas: 2
  selector:
    app: selenium-node-chrome
  template:
    metadata:
      name: selenium-node-chrome
      labels:
        app: selenium-node-chrome
    spec:
      containers:
        - name: selenium-node-chrome
          image: selenium/node-chrome
          ports:
            - containerPort: 5900
          env:
            - name: SE_EVENT_BUS_HOST
              value: "hub-service"
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
            - name: SE_NODE_MAX_SESSIONS
              value: "5"
            - name: SE_NODE_OVERRIDE_MAX_SESSIONS
              value: "true"